cloudendpoints/endpoints-java

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/EndpointsToolAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GenApiConfigAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetClientLibAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetDiscoveryDocAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetSwaggerDocAction.java
- endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/EndpointsToolActionTest.java
- endpoints-framework-tools/src/test/resources/com/google/api/server/spi/tools/web.xml
The command line tools currently require the user to type in the service
class names to generate API configuration. This change makes it so that
if the user doesn't specify any classes, it attempts to read the
information from the web.xml instead.
> read web.xml service classes if none are passed in

- endpoints-framework/src/main/java/com/google/api/server/spi/response/UnauthorizedException.java
In the old framework version, a different value for the WWW-Authenticate
header was returned. This change simply returns to this existing
behavior.
> fix default behavior of UnauthorizedException

- build.gradle
- endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/EndpointsToolActionTest.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiNamespace.java
- Define source encoding in gradle
- Fix tests assuming file separator is /
- Remove non-UTF-8 chars in Javadoc (couldn't find an easy way to tell the gradle javadoc command to use UTF-8)
> Fix build on Windows

- endpoints-framework/src/main/java/com/google/api/server/spi/Constant.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/IssuerUtil.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiIssuerConfigs.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_default_context.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_internal.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_localhost.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/google_auth.swagger
All the JWT tokens issued by Google currently have https://accounts.google.com as their issuer.
Below is an example of a JWT token generated today using the OAuth2 playground.
```
{
"iss": "https://accounts.google.com",
"at_hash": "***",
"aud": "***",
"sub": "***",
"email_verified": true,
"azp": "***",
"hd": "***",
"email": "***",
"iat": 1476203989,
"exp": 1476207589
}
```
It seems like the issuer has been changing back and forth from "accounts.google.com" to "https://accounts.google.com" recently (see my comment on [this post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-cloud-endpoints/Rkfi0yMU93E/AGfMXB4ECQAJ))
This change switches back to https://accounts.google.com as the issuer, it fixes the [endpoints v2 backend …
> Use "https://accounts.google.com" as issuer to validate JWT tokens

- endpoints-framework/src/main/java/com/google/api/server/spi/config/Api.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiClass.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiMethod.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiAnnotationConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiClassAnnotationConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiMethodAnnotationConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiClassConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/swagger/SwaggerGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/api_keys.swagger
This change doesn't actually add API key validation, since that's done
in the endpoints-management libraries. This simply adds Swagger
generation so that the the management filter knows to do the validation.
To keep things simple, we provide a boolean true or false and fix the
API key to be a query parameter named "key". This is in line with what
client libraries expect.
> add support for API keys in Swagger generation

- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/IssuerUtil.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
Right now, the legacy audiences directly impact the data structures used
for third party JWT issuers. However, if you add audiences below the
@Api level, then this means some ApiConfig objects will have Google
issuer configs and some will not. This change removes the effect of the
legacy audiences on the new and instead lets other code merge them as
necessary, to keep the model consistent.
> de-couple new and old audiences in the model

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/AppEngineUtil.java
Right now, AppEngineUtil supports reading from war/WEB-INF/app.yaml or
war/WEB-INF/appengine-web.xml. However, staged apps need to read
properties from war/app.yaml.
> support reading properties from war/app.yaml

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/EndpointsToolAction.java
Flex apps are unlikely to specify the app id in app.yaml, so they need
to specify the hostname manually. Later, we should add some better
diagnostic messages around this, but for now we just do lazy evaluation
to make OpenAPI generation work.
> lazily evaluate application default hostname

- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java
This change allows an API to subclass the Endpoints User class to add
more information. This enables more flexibility for custom
authenticators.
> make User subclassable for custom authenticators

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GenApiConfigAction.java
- endpoints-framework/src/main/java/com/google/api/server/spi/SystemService.java
- endpoints-framework/src/main/java/com/google/api/server/spi/TypeLoader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/validation/ApiConfigValidator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriterTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/validation/ApiConfigValidatorTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java
- test-utils/src/main/java/com/google/api/server/spi/BaseSystemServiceTest.java
- test-utils/src/main/java/com/google/api/server/spi/testing/CollectionContravarianceEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/CollectionCovarianceEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/DuplicateMethodEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/SimpleContravarianceEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/SimpleCovarianceEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/SimpleOverloadEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/TestEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/TestEndpointSuperclass.java
This change moves config validation out of JsonConfigWriter into
ApiConfigValidator. JsonConfigWriter is mostly deprecated at this point,
with no need for the older JSON API config with discovery and Swagger
generation being created without it.
* Fixed a potential performance issue in which classes were re-validated
constantly after each new Endpoint class registration. Now,
SystemService.Builder triggers a validation of all APIs after class
registration is finished.
* registerInternalService has been removed. BackendService is the only
class that utilized this, and it has been removed.
* resolveAndUpdateServiceConfig has been removed. Dynamic datastore
config reloads are no longer supported.
* Correctly allow byte arrays and datastore Blobs as parameter
types. Both of these are …
> refactor and cleanup API config validation

- endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/AnnotationApiConfigGeneratorTest.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/annotationreader/ApiAnnotationConfigTest.java
The feature of "hiding" some versions of the API explorer is actually quite useful (["Services"](https://developers.google.com/apis-explorer/#p/) vs. ["All versions"](https://developers.google.com/apis-explorer/#s/)). 
Many of our APIs have unstable versions "v1betaN" that we want to make less visible to end users with this feature.
This PR allows to "hide" APIs again, by honoring the "defaultVersion" field on @Api annotations.
But it does not replicate the behavior of the legacy endpoints, that was automatically choosing one version if multiple APIs had the same name (I actually was not able to determine the rule for this).
> Reenable support for "preferred" flag in the discovery list

- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/SchemaRepository.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/model/ApiMethodConfigTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/model/SchemaRepositoryTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/discovery/DiscoveryGeneratorTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/swagger/SwaggerGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/absolute_common_path_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/absolute_path_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/absolute_common_path_endpoint.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/absolute_path_endpoint.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_default_context.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_internal.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_localhost.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/google_auth.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/third_party_auth.swagger
- test-utils/src/main/java/com/google/api/server/spi/testing/AbsoluteCommonPathEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/AbsolutePathEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/EnumEndpointV2.java
- test-utils/src/main/java/com/google/api/server/spi/testing/EnumValue.java
* Methods with absolute paths should now generate the correct discovery output. The common path prefix builder is used to compute the service path and basepath using methods' canonical paths (including API name and version). A method with a path of `/notinanyapipath` will result in a blank service path and a base URL of the Endpoints root path.
* Resources that are shared across multiple APIs now correctly have their field schema added to the API as well.
> fix discovery and OpenAPI generation

- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
This case was broken by the refactoring to allow User subclass
injection, since it checks the User object's class for
assignability. This check is now skipped if the value is null.
> fix NPE caused by missing credentials

- endpoints-framework-all/build.gradle
Currently, dependencies are repackaged in the JAR, but the framework
classes aren't rewritten. This fixes the problem.
> fix shadow JAR distribution

- endpoints-framework/src/main/java/com/google/api/server/spi/handlers/ExplorerHandler.java
- endpoints-framework/src/test/java/com/google/api/server/spi/handlers/ExplorerHandlerTest.java
API Explorer does not allow http://host:80 or https://host:443, which is
what we get from the servlet container. This change removes the port
numbers in these cases.
> strip redundant port numbers to fix API Explorer

- endpoints-framework/src/main/java/com/google/api/server/spi/SystemService.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/Authenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/Auth.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/ParamReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
This feature request lets Authenticators throw ServiceExcpetions, which
are then written in the standard JSON format. This change also refactors
exception handling when calling an API method to clean up the logic a
bit, and change the logging level so that 5xx-level ServiceExceptions
log at the WARNING level, and others at INFO.
> allow Authenticators to throw ServiceException

- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/SchemaRepository.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/model/SchemaRepositoryTest.java
Currently, if you add a self-referencing type to multiple APIs, a
StackOverflowError will occur. This change fixes that by not attempting
to add a type to an API that's already added.
> fix stack overflow issue with recursive schema

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetDiscoveryDocAction.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/validation/ApiConfigValidator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriterTest.java
It seems this is not behaving as it was before. Instead of throwing an
exception, we now log a warning, so it's allowed, but discouraged.
> disable property/field name conflict validation

- endpoints-framework/src/main/java/com/google/api/server/spi/handlers/ApiProxyHandler.java
Sometimes this gets set by a web server to other values, but by design,
this handler needs to be injectable in any origin.
> set X-Frame-Options in proxy.html handler

- endpoints-framework/src/main/java/com/google/api/server/spi/ObjectMapperUtil.java
- endpoints-framework/src/test/java/com/google/api/server/spi/discovery/DiscoveryGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/absolute_path_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/absolute_path_endpoint.swagger
- test-utils/src/main/java/com/google/api/server/spi/testing/AbsolutePathEndpoint.java
The discovery test was not catching this issue in part because it wasn't
using the exact same JSON serialization as it does at runtime. That has
also been fixed. This change will likely reintroduce empty maps in
serialization, but this is currently the best workaround to allow empty
strings inside maps, which we need to serialize the discovery document
correctly.
> fix empty servicePath in discovery

- endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java
On flex env, it seems like custom headers set on the response after writing to the body are not always being written to the final http response.
This causes CORS support not to work with Cloud Endpints v2 on flex env (it works fine on AppEngine standard though).
Simply changing the code to write CORS headers before the response body fixes the issue.
Additionally, it makes any backend error that would happen available to CORS clients as well.
> Set CORS-related headers before writing body for flex env support

- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleAuth.java
This allows a custom authenticator to fetch the token.
> make GoogleAuth.getAuthToken() public

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/EndpointsToolAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetClientLibAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetDiscoveryDocAction.java
- endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/GetClientLibActionTest.java
- endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/GetDiscoveryDocActionTest.java
- endpoints-framework/src/main/java/com/google/api/server/spi/ServiceContext.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiConfig.java
- endpoints-framework/src/test/java/com/google/api/server/spi/ServiceContextTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/annotationreader/ApiAnnotationConfigTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReaderTest.java
App Engine is deprecating app IDs in config and we want to get away from
this model anyway. This change adds --hostname and --path to
get-discovery-doc and get-client-lib to fully specify where an API is
hosted. This involves the following code changes:
* refactor of ServiceContext to allow specifying a hostname instead of
just an app id
* Renamed the appHostName property to appHostname in ServiceContext
* debug flag in get-discovery-doc is now a no-op. It really already was,
but now it has been removed from the code except for the interface
itself so we don't break anyone. It stopped outputting intermediate
files because there no longer are any.
* small cleanups (removed extra space, unused CLI options, test
formatting adjustments)
> use hostname and path flags in all of the CLI

- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiAnnotationIntrospector.java
- test-utils/src/main/java/com/google/api/server/spi/testing/Foo.java
Currently, if a resource field has a private accessor, instance field
and mutator, the resource is still exposed as if it were public. For
some reason, Jackson defaults to allowing mutators of any visibility
level to count as an exposed field, while requiring instance fields and
accessors to be public to count.
This change fixes a longstanding (from v1) bug by hiding such
cases. Resources will now only have exposed fields when at least one
part of the field declaration (field itself, accessor, or mutator) is
public.
> hide all private resource fields

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/EndpointsToolAction.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetClientLibAction.java
* get-client-lib reversed the hostname and base path parameters sent to
GetDiscoveryDocAction.
* get-client-lib gave a null hostname rather than myapp.appspot.com if
-h and appengine-web.xml didn't have an app id.
> fix hostname generation in get-client-lib

- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/SchemaRepository.java
- endpoints-framework/src/test/java/com/google/api/server/spi/discovery/DiscoveryGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/array_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/array_endpoint.swagger
- test-utils/src/main/java/com/google/api/server/spi/testing/ArrayEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/StringValue.java
- test-utils/src/main/java/com/google/api/server/spi/testing/StringValueTransformer.java
When a Transformer affects an array element type, SchemaRepository
treated it as the non-transformed type. If the Transformer transformed
to a primitive, SchemaRepository tried to add the primitive as an object
schema, resulting in an error. This fixes that by getting the schema
type when dealing with array types.
> fix schema generation for transformer corner case

- endpoints-framework/src/main/java/com/google/api/server/spi/handlers/ApiProxyHandler.java
This is essentially a no-op, since proxy.html no longer contains the
/_ah/api string. All this does is save CPU cycles
> don't try to substitute proxy.html base path

- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiIssuerAudienceConfig.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiIssuerConfigs.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/model/ApiIssuerAudienceConfigTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_default_context.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_internal.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_endpoint_localhost.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/google_auth.swagger
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/third_party_auth.swagger
The new auth format specifies audiences in the OpenAPI security
definitions block, rather than using the x-security vendor
extension. To handle this, we now declare one security definition per
issuer-audience set combination. The security definition is given the
name of the issuer plus a hash of the audience set in hexadecimal.
> update OpenApi spec generation to new auth format

- .travis.yml
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/foo_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/foo_endpoint_default_context.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/foo_endpoint_localhost.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/multiple_parameter_endpoint.json
- test-utils/src/main/java/com/google/api/server/spi/testing/MultipleParameterEndpoint.java
Discovery has a parameterOrder field. This is seemingly used to
document the order of parameters for use in client library
generation. Previously, we were only including path parameters, but we
need to include query parameters, so that the order is deterministic.
> include query parameters in parameterOrder field

- endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java
It is currently not easy to support all AuthLevel modes, but REQUIRED
is likely to be the the most used and easy to implement, so support is
added here.
> support AuthLevel.REQUIRED annotation

- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/swagger/SwaggerGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/api_keys.swagger
Right now, if wishing to use JWT auth plus API keys, the OpenAPI
config generator places the API key in a separate security
requirement, which allows JWT auth OR API key. This change adds the
API key to every existing security requirement to change OR to AND. If
no current security requirements exist, a new one is created to solely
allow API key validation.
> fix JWT + API key auth config generation

- endpoints-framework/src/main/java/com/google/api/server/spi/response/RestResponseResultWriter.java
- endpoints-framework/src/test/java/com/google/api/server/spi/response/RestResponseResultWriterTest.java
Currently a NullPointerException is thrown due to disallowed null
values in ImmutableMap. This change changes error construction to use
Jackson data to allow for null values.
> allow null error fields

- endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiResourceProperty.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/ResourcePropertySchema.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiAnnotationIntrospector.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JacksonResourceSchemaProvider.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/Schema.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/SchemaRepository.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/jsonwriter/ResourceSchemaProviderTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/discovery/DiscoveryGeneratorTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/swagger/SwaggerGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/foo_with_description_endpoint.json
- endpoints-framework/src/test/resources/com/google/api/server/spi/swagger/foo_with_description_endpoint.swagger
- test-utils/src/main/java/com/google/api/server/spi/testing/FooDescription.java
- test-utils/src/main/java/com/google/api/server/spi/testing/FooDescriptionEndpoint.java
This PR adds support for description on resource fields, using an new  description field on @ApiResourceProperty annotation.
> Add description on resource fields

- endpoints-framework/src/main/java/com/google/api/server/spi/config/Description.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/model/SchemaRepository.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/config/jsonwriter/ResourceSchemaProviderTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/discovery/DiscoveryGeneratorTest.java
- endpoints-framework/src/test/resources/com/google/api/server/spi/discovery/foo_with_description_endpoint.json
- test-utils/src/main/java/com/google/api/server/spi/testing/FooDescription.java
- test-utils/src/main/java/com/google/api/server/spi/testing/FooDescriptionEndpoint.java
- test-utils/src/main/java/com/google/api/server/spi/testing/TestEnumDescription.java
This PR allows to set a description on enum values in API method parameters, as allowed in the discovery format.
- The DiscoveryGenerator [already supported enum descriptions](https://github.com/cloudendpoints/endpoints-java/blob/master/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java#L230).
- The OpenAPI format does not support descriptions on enum values ([yet](https://github.com/OAI/OpenAPI-Specification/issues/348)).
PS: we tried to implement description for enums in Swagger [here](https://github.com/AODocs/endpoints-java/tree/enum_description_in_swagger), as described in [Swagger documentation for enums](https://swagger.io/docs/specification/data-models/enums/), using the description field, but we preferred not to include it yet.
> Add description on enum constants

- endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java
This change fixes path parameter deserialization when the parameter is
an array-like structure. Previously, this only worked for query
parameters, and a string literal was injected as an array for path
parameters.
> fix array path parameter deserialization

- endpoints-framework/src/main/java/com/google/api/server/spi/auth/EndpointsAuthenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleAppEngineAuthenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleAuth.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleOAuth2Authenticator.java
- endpoints-framework/src/test/java/com/google/api/server/spi/auth/EndpointsAuthenticatorTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/auth/GoogleAppEngineAuthenticatorTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/auth/GoogleAuthTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/auth/GoogleOAuth2AuthenticatorTest.java
We are using Cloud Endpoints to serve a large scale API (millions of API requests per day).
We measure a low but significant amount of transient "503/backend error" when validating OAuth2 requests with GoogleAuth#getTokenInfoRemote, that translates into a "401/UnauthorizedException" for the API clients => this is not what one would expect for a transient exception.
This pull request introduce two main changes:
- It performs a single, immediate retry on https://www.googleapis.com/oauth2/v2/tokeninfo?access_token=XXX  for IOExceptions and 5xx responses
- If the retry on IOException or 5xx fails, a "503/ServiceUnavailableException" is returned to API client, instead of a "401/UnauthorizedException"
> Handle properly Google's tokeninfo 503/backend error

- endpoints-framework/src/main/java/com/google/api/server/spi/config/validation/ApiConfigValidator.java
The official documentation for a long time has disallowed underscores
in API names, so I'm leaving it as such. However, for extremely old
users of the old frameworks, this limitation was not in
place. Therefore, I'm removing it from the API validation, but leaving
the @Api documentation in order to not encourage the style.
> quietly allow underscores in API names

- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java
- endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java
@Named parameters that don't have @Nullable parameters are deemed
required. Endpoints v2 lost this request validation, but this change
adds it back in. Previously, the framework would assume the validation
was done.
> check non-nullness of required parameters

- endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java
If an enum was misspelled, this printStrackTrace spammed the logs with WARNING lines.
>  Replaced printStackTrace() with JUL

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/EndpointsTool.java
- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GetOpenApiDocAction.java
> endpoints tool fixes

- endpoints-framework/build.gradle
- endpoints-framework/src/main/java/com/google/api/server/spi/BackendProperties.java
- endpoints-framework/src/main/java/com/google/api/server/spi/ConfiguredObjectMapper.java
- endpoints-framework/src/main/java/com/google/api/server/spi/SystemService.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/EndpointsPeerAuthenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleAppEngineAuthenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleAuth.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleJwtAuthenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/auth/GoogleOAuth2Authenticator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/Singleton.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JacksonResourceSchemaProvider.java
- endpoints-framework/src/main/java/com/google/api/server/spi/config/validation/ApiConfigValidator.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/AbstractDiscoveryProvider.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/CachingDiscoveryProvider.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/ProxyingDiscoveryProvider.java
- endpoints-framework/src/main/java/com/google/api/server/spi/discovery/ProxyingDiscoveryService.java
- endpoints-framework/src/main/java/com/google/api/server/spi/dispatcher/PathTrie.java
- endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java
- endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java
- gradle.properties
* This should fix the few broken log statements throughout due to
misunderstanding log string formatting
* Log performance should be generally increased by saving string
format operations unless they're necessary
> convert standard logging to use flogger

- endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/GenApiConfigAction.java
Files.write is deprecated and scheduled for removal. Changing this to use Files.asCharSink().write() is the same implementation, but is not deprecated.
> Inline Files.write() in GenApiConfigAction
